name: news_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cached_network_image: ^3.4.1
  equatable: ^2.0.5
  floor: ^1.5.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_hooks: ^0.20.5
  get_it: ^8.0.0
  intl: ^0.19.0
  retrofit: ^4.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  retrofit_generator: ^9.1.2
  floor_generator: ^1.5.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
